package Tool_Types {
    /**
     * Enumeration of standard Digital Engineering tool categories.
     */
    enum def Tool_Type_e {
    '1 Physical System Representation';
    '1.1 Computer Aided Design (CAD)';
    '1.2 Electrical computer-aided design (ECAD)';
    '1.3 Product Lifecycle Management (PLM)';
    '2 Simulations';
    '2.1 Low Fidelity Simulations';
    '2.2 Computational Fluid Dynamics (CFD)';
    '2.3 Finite Element Analysis (FEA)';
    '2.4 Electromagnetic (EM)';
    '2.5 Dynamic Simulations';
    '2.6 Mission Models';
    '2.7 Simulation Managers';
    '3 Model Based System-Engineering (MBSE) and System Architecture and Design Tools';
    '3.1 Requirements Management Tools';
    '3.2 Architecture Tools';
    '3.3 Shared Architecture Tools';
    '4 Computer Science and Software Engineering Tools';
    '4.1 Integrated Development Environments (IDEs)';
    '4.2 Version Control Systems';
    '4.3 Continuous Integration/Continuous Deployment (CI/CD)';
    '4.4 Testing Frameworks';
    '5 Data Integration';
    '5.1 Data Analytics and Visualization';
    '5.2 Data Integration';
    '5.3 Data Persistence';
    '5.4 Digital Thread';
    '6 Manufacturing';
    '6.1 Physical Product Definition and Representation';
    '6.2 Process Modeling & Simulation';
    '6.3 Manufacturing Execution Software (MES)';
    '7 Logistics';
    '7.1 Supply Chain Planning & Optimization';
    '7.2 Transportation and Distribution Management';
    '7.3 Inventory Management';
    '7.4 Sustainment and Maintenance';
    '8 Productivity Tools in Digital Engineering';
    '8.1 Word Processing and Document Collaboration';
    '8.2 Presentation Software';
    '8.3 Spreadsheets';
    '8.4 Email and Communication Platforms';
    '8.5 Task Management and Project Planning';
    '8.6 Shared Drives and Cloud Storage';
    '9 Host Platform';
    '10 Cybersecurity';
    }
}